version: '3.8'

services:
  http-api:
    build:
      context: .
      dockerfile: HttpApi/Dockerfile
    ports:
      - "5000:80"
      - "5443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  websocket-api:
    build:
      context: .
      dockerfile: WebsocketApi/Dockerfile
    ports:
      - "5001:80"
      - "5444:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  angular-app:
    build:
      context: ./path-to-your-angular-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"
