version: '3.8'

services:
  httpapi:
    image: tomdra01/httpapi:prod

  wsapi:
    image: tomdra01/wsapi:prod

  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
      args:
        - configuration=production
    image: tomdra01/frontend:prod

  flyway:
    environment:
      FLYWAY_URL: jdbc:postgresql://167.86.96.91:5432/${DB_USER}