version: '3.8'

services:
  httpapi:
    image: tomdra01/httpapi:prod

  wsapi:
    image: tomdra01/wsapi:prod

  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
      args:
        - configuration=production
    image: tomdra01/frontend:prod

  flyway:
    image: flyway/flyway
    depends_on:
      - postgres
    command: migrate
    volumes:
      - ./db/:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://167.86.96.91:5432/${DB_USER}
      FLYWAY_USER: ${DB_USER}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
      FLYWAY_SCHEMAS: production