name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-push-httpapi:
    name: Build and Push HttpApi Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push HttpApi image
        env:
          DB_CON: ${{ secrets.DB_CON }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          cd backend
          docker compose build httpapi
          docker tag tomdra01/httpapi:prod tomdra01/httpapi:prod
          docker push tomdra01/httpapi:prod

  build-and-push-wsapi:
    name: Build and Push WsApi Image
    runs-on: ubuntu-latest
    needs: [ integration-tests, static-code-analysis ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push WsApi image
        env:
          DB_CON: ${{ secrets.DB_CON }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          cd backend
          docker compose build wsapi
          docker tag tomdra01/wsapi:prod tomdra01/wsapi:prod
          docker push tomdra01/wsapi:prod

  build-and-push-frontend:
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest
    needs: [ integration-tests, static-code-analysis ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push frontend image
        env:
          DB_CON: ${{ secrets.DB_CON }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          cd backend
          docker compose build frontend --build-arg configuration=production
          docker tag tomdra01/frontend:prod tomdra01/frontend:prod
          docker push tomdra01/frontend:prod

  trigger-update-and-deploy:
    name: Deploy to Production environment
    needs: [ build-and-push-docker-images ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger update
        run: |
          curl --fail -X GET 'http://167.86.96.91:8090/v1/update' -H 'Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}'

      - name: Cooldown 10s
        run: sleep 10

  database-migration:
    name: Database Migration
    runs-on: ubuntu-latest
    needs: [ trigger-update-and-deploy ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - run: |
          cd backend
          sleep 10
          docker compose up flyway