name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    permissions:
      contents: read
      packages: read
      id-token: write

  static-code-analysis:
    needs: setup
    uses: ./.github/workflows/static-code-analysis.yml
    permissions:
      contents: read