name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  static-code-analysis:
    name: static-code-analysis
    runs-on: windows-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v3  
        with:
          fetch-depth: 0  
      - name: Set up JDK 17
        uses: actions/setup-java@v3 
        with:
          distribution: 'temurin'  
          java-version: 17
      - name: Cache SonarQube packages
        uses: actions/cache@v3 
        with:
          path: ~\.sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarQube scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3 
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          dotnet tool install --global dotnet-sonarscanner
      - name: Add .dotnet tools to PATH
        shell: powershell
        run: |
          $env:PATH += ";$env:USERPROFILE\.dotnet\tools"
          [System.Environment]::SetEnvironmentVariable('PATH', $env:PATH, [System.EnvironmentVariableTarget]::Process)
      - name: Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        shell: powershell
        working-directory: ./backend  
        run: |
          dotnet-sonarscanner begin /k:"VahPheephoopou2" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

  database-migration:
    name: Database Migration
    runs-on: ubuntu-latest
    needs: static-code-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flyway
        run: |
          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.13/flyway-commandline-8.5.13-linux-x64.tar.gz | tar xvz && ln -s `pwd`/flyway-8.5.13/flyway /usr/local/bin

      - name: Migrate Database
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          flyway -url=${DB_URL} -user=${DB_USER} -password=${DB_PASSWORD} -locations=filesystem:./db/migration migrate

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [static-code-analysis, database-migration]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: |
          cd backend && cd HttpApi
          dotnet restore

      - name: Build the test project
        run: |
          cd backend && cd test
          dotnet build --no-restore

      - name: Start Web API
        env:
          DB_CON: ${{ secrets.DB_CON }}
          UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          cd backend && cd HttpApi
          dotnet run & echo "API_PID=$!" >> $GITHUB_ENV
          sleep 30

      - name: Run API tests
        run: |
          cd backend && cd test
          dotnet test --no-build

      - name: Shutdown Web API
        if: always()
        run: kill $API_PID