name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy-to-test-environment:
    name: Deploy to Test environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger update
        run: |
          curl --fail -X GET 'http://164.68.109.76:8090/v1/update' -H 'Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}'

      - name: Cooldown 10s
        run: sleep 10