name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - pipeline/watch-test

jobs:
  trigger-update-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger update
        run: |
          curl --fail -X GET 'http://164.68.109.76:8090/v1/update' -H 'Authorization: Bearer authtoken'

      - name: Sleep for cooldown
        run: sleep 10

      - name: Test Dir Location
        run: ls -la
        working-directory: .

      - name: Deploy services using Docker Compose
        run: docker-compose up -d
        working-directory: ../

      - name: Check service status
        run: docker-compose ps
        working-directory: ../
