name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - pipeline/flyway-imp

jobs:
  end-to-end-tests:
    needs: update-database
    runs-on: ubuntu-latest
    container:
      image: testcafe/testcafe
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
      - name: Run End-to-End Tests
        run: npx testcafe chromium:headless ./frontend/test-cafe/angular-test.js