name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - pipeline/flyway-imp

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run End-to-End Tests
        run: |
          npx testcafe chromium:headless ./frontend/test-cafe/angular-test.js --page-request-timeout 30000 --retry-test-pages --quarantine-mode